### ISSUE TITLE
Compile error on Windows 8.1

### ISSUE THREAD

**Issue by Ivo-Balbaert** [rust-lang/time#107]
When I make an empty cargo project with 
[dependencies]
time = "*"
I get the following compile error on Windows 8.1 , 64 bit, Rust stable 1.1:

F:\Rust\programs\web frameworks\using_time>cargo build
   Compiling time v0.1.26
failed to run custom build command for `time v0.1.26`
Process didn't exit successfully: `F:\Rust\programs\web frameworks\using_ti
get\debug\build\time-f08bec52f4924e95\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
CARGO_MANIFEST_DIR = Some("C:\\Users\\CVO\\.cargo\\registry\\src\\github.co
6299db9ec823\\time-0.1.26")
OUT_DIR = Some("F:\\Rust\\programs\\web frameworks\\using_time\\target\\deb
ild\\time-f08bec52f4924e95\\out")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
running: "gcc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-mwin32"
" "-fPIC" "C:\Users\CVO\.cargo\registry\src\github.com-1ecc6299db9ec823\tim
26\src/time_helpers.c" "-o" "F:\Rust\programs\web frameworks\using_time\tar
bug\build\time-f08bec52f4924e95\out\src\time_helpers.o"

command did not execute successfully, got: exit code: 1

--- stderr
C:\Users\CVO\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.26\sr
_helpers.c:1:0: let op: -fPIC ignored for target (all code is position inde
t) [enabled by default]
C:\Users\CVO\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.26\sr
_helpers.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
thread '<main>' panicked at 'explicit panic', C:\Users\CVO\.cargo\registry\
thub.com-1ecc6299db9ec823\gcc-0.3.8\src\lib.rs:497

Before this error I get a popup window with the error: File std-7d23ff90.dll is missing or corrupt,
but that file is there in bin folder. A repair or re-install does not solve the problem.
What could I do to solve this problem ?

Thanks,
Ivo

**Comment by alexcrichton** [comment]
This looks like you're in a MSYS-32 shell when you need to be in a MSYS-64 shell, specifically:

```
sorry, unimplemented: 64-bit mode not compiled in
```

Switching to the other shell should do the trick!
