### ISSUE TITLE
 error: failed to resolve. Use of undeclared type or module libc

### ISSUE THREAD

**Issue by tadman** [rust-lang/time#108]
Looks like something slipped in the newest version vs. Rust 1.1.0 on OS X 10.10:

    Compiling time v0.1.27
    /Users/tadman/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.27/src/sys.rs:123:26: 123:39 error: failed to resolve. Use of undeclared type or module `libc`
    /Users/tadman/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.27/src/sys.rs:123             let mut tv = libc::timeval { tv_sec: 0, tv_usec: 0 };
                                                                                                                  ^~~~~~~~~~~~~
    /Users/tadman/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.27/src/sys.rs:123:26: 123:39 error: `libc::timeval` does not name a structure
    /Users/tadman/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.27/src/sys.rs:123             let mut tv = libc::timeval { tv_sec: 0, tv_usec: 0 };

**Comment by tadman** [comment]
@alexcrichton Thanks for fixing this quickly. The build was passing at the time, so it might be worth expanding the coverage there to non-Windows platforms.

**Comment by alexcrichton** [comment]
Unfortunately there's no great solution for OSX CI (in the free open source sense), but we're already testing on two targets on Windows and on Linux, so we're pretty well covered :)

**Comment by tadman** [comment]
Surprised the Linux build didn't trip.

The builds I'm seeing in your CI link are only:

> Environment: TARGET=x86_64-pc-windows-msvc
> Environment: TARGET=i686-pc-windows-gnu

Windows and Windows?

**Comment by alexcrichton** [comment]
https://travis-ci.org/rust-lang/time

**Comment by tadman** [comment]
Right you are. Thanks!
