### ISSUE TITLE
Windows build error: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/time#56]
I get the following error when trying to build time on Windows 7, 64bit system...

~~~
failed to run custom build command for `time v0.1.12`
Process didn't exit successfully: `C:\Users\alchemist\Documents\Rusty\face-blaster\target\build\time-7c7fc3eb0c12ad75\bu
ild-script-build.exe` (status=101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CARGO_MANIFEST_DIR = Some("C:\\Users\\alchemist\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\time-0.1.12")
OUT_DIR = Some("C:\\Users\\alchemist\\Documents\\Rusty\\face-blaster\\target\\build\\time-7c7fc3eb0c12ad75\\out")
running: gcc '-O0' '-c' '-ffunction-sections' '-fdata-sections' '-mwin32' '-m64' '-fPIC' 'C:\Users\alchemist\.cargo\regi
stry\src\github.com-1ecc6299db9ec823\time-0.1.12\src\time_helpers.c' '-o' 'C:\Users\alchemist\Documents\Rusty\face-blast
er\target\build\time-7c7fc3eb0c12ad75\out\src\time_helpers.o'

--- stderr
C:\Users\alchemist\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.12\src\time_helpers.c:1:0: warning: -fPIC ig
nored for target (all code is position independent) [enabled by default]
// Copyright 2012 The Rust Project Developers. See the COPYRIGHT
^
C:\Users\alchemist\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.12\src\time_helpers.c:1:0: sorry, unimplemen
ted: 64-bit mode not compiled in
thread '<main>' panicked at 'nonzero exit status: exit code: 1', C:\Users\alchemist\.cargo\registry\src\github.com-1ecc6
299db9ec823\gcc-0.1.4\src\lib.rs:125
~~~

**Comment by AndyShiue** [comment]
$ cargo build
   Compiling gcc v0.1.4
   Compiling time v0.1.12
failed to run custom build command for `time v0.1.12`
Process didn't exit successfully: `D:\root\Language_Performance_Contest\Prime\Rust\target\build\time-7c7fc3eb0c12ad75\build-script-build.exe` (status=101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CARGO_MANIFEST_DIR = Some("C:\\msys64\\home\\Administrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\time-0.1.12")
OUT_DIR = Some("D:\\root\\Language_Performance_Contest\\Prime\\Rust\\target\\build\\time-7c7fc3eb0c12ad75\\out")
running: gcc '-O0' '-c' '-ffunction-sections' '-fdata-sections' '-mwin32' '-m64' '-fPIC' 'C:\msys64\home\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.12\src\time_helpers.c' '-o' 'D:\root\Language_Performance_Contest\Prime\Rust\target\build\time-7c7fc3eb0c12ad75\out\src\time_helpers.o'

I also hit this.

**Comment by AndyShiue** [comment]
64-bit Windows 8 here

**Comment by alexcrichton** [comment]
This typically means that you're running in a 32-bit MSYS shell instead of a 64-bit MSYS shell. Could you guys confirm that you're running in the 64-bit shell?

**Comment by nathansizemore** [comment]
32-bit MSYS was the culprit in my case.

**Comment by nathansizemore** [comment]
Closing issue, fixed my case
