### ISSUE TITLE
libtime::Tm::to_utc() is slow even if already utc

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/time#66]
<a href="https://github.com/seanmonstar"><img src="https://avatars.githubusercontent.com/u/51479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seanmonstar](https://github.com/seanmonstar)**
_Friday Nov 07, 2014 at 01:29 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18725_

_This issue was labelled with:  in the Rust repository_

----

`Tm.to_utc()` calls out to the runtime fn `rust_timegm` twice, once to convert to a Timespec, and a second time to convert the timespec to a new Tm with offset of 0. If a `Tm` is already UTC, this should skip both those calls.

**Comment by zslayton** [comment]
Is this as simple as:
```rust
    /// Convert time to the UTC
    pub fn to_utc(&self) -> Tm {
        match self.tm_utcoff {
          0 => *self,
          _ => at_utc(self.to_timespec())
        }
    }
```
? If so, I'd be happy to put together a pull request!
