### ISSUE TITLE
Cannot compile on windows

### ISSUE THREAD

**Issue by natemara** [rust-lang/time#69]
I'm using the latest version of the rust compiler on Windows to compile rust-crypto, which depends on time. I am getting the following error when I try and build my project.

    $ rustc --version
    rustc 1.0.0-nightly (74b874071 2015-02-08 00:24:03 +0000)

    $ cargo build --verbose
           Fresh libc v0.1.2
           Fresh log v0.2.2
           Fresh gcc v0.1.7
           Fresh rustc-serialize v0.2.12
           Fresh rand v0.1.2
           Fresh getopts v0.2.3
           Fresh time v0.1.16
           Fresh rust-crypto v0.2.15
       Compiling deduper v0.0.1 (file:///F:/Coding/rust-deduper)
         Running `rustc main.rs --crate-name deduper --crate-type bin -g --out-dir F:\Coding\rust-deduper\target --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target -L dependency=F:\Coding\rust-deduper\target\deps --extern crypto=F:\Coding\rust-deduper\target\deps\libcrypto-24da0b4009abc223.rlib --extern getopts=F:\Coding\rust-deduper\target\deps\libgetopts-a6c123c21f99fb4b.rlib -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out`
    main.rs:12:5: 12:21 warning: unused import, #[warn(unused_imports)] on by default
    main.rs:12 use getopts::Options;
                   ^~~~~~~~~~~~~~~~
    main.rs:15:16: 15:24 warning: use of deprecated item: use env::args instead, #[warn(deprecated)] on by default
    main.rs:15     let args = os::args();
                              ^~~~~~~~
    main.rs:42:9: 42:71 warning: unused result which must be used, #[warn(unused_must_use)] on by default
    main.rs:42         out_file.write_str(format!("{}\n", dup.display()).as_slice());
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: linking with `gcc` failed: exit code: 1
    note: "gcc" '"-Wl,--enable-long-section-names"' '"-fno-use-linker-plugin"' '"-Wl,--nxcompat"' '"-static-libgcc"' '"-m64"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-o"' '"F:\\Coding\\rust-deduper\\target\\deduper.exe"' '"F:\\Coding\\rust-deduper\\target\\deduper.o"' '"-Wl,--gc-sections"' '"F:\\Coding\\rust-deduper\\target\\deps\\libcrypto-24da0b4009abc223.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\libtime-69a93874bd2e0ce7.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\librustc-serialize-db8cde5690079042.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\librand-786334d103466ef3.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\liblibc-8d21de95f4de7169.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\libgetopts-a6c123c21f99fb4b.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunicode-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-4e7c5e5c.rlib"' '"-L"' '"F:\\Coding\\rust-deduper\\target"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\deps"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\build\\time-69a93874bd2e0ce7\\out"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-L"' '"F:\\Coding\\rust-deduper\\src\\.rust\\bin\\x86_64-pc-windows-gnu"' '"-L"' '"F:\\Coding\\rust-deduper\\src\\bin\\x86_64-pc-windows-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lws2_32"' '"-luserenv"' '"-lcompiler-rt"'
    note: F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::tzset':
    C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:599: undefined reference to `rust_time_tzset'
    F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::at_utc':
    C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:703: undefined reference to `rust_time_gmtime'
    F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::Tm::to_timespec':
    C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:733: undefined reference to `rust_time_timegm'
    C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:734: undefined reference to `rust_time_mktime'
    F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::at':
    C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:718: undefined reference to `rust_time_localtime'

    error: aborting due to previous error
    Could not compile `deduper`.

    Caused by:
      Process didn't exit successfully: `rustc main.rs --crate-name deduper --crate-type bin -g --out-dir F:\Coding\rust-deduper\target --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target -L dependency=F:\Coding\rust-deduper\target\deps --extern crypto=F:\Coding\rust-deduper\target\deps\libcrypto-24da0b4009abc223.rlib --extern getopts=F:\Coding\rust-deduper\target\deps\libgetopts-a6c123c21f99fb4b.rlib -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out` (status=101)

Is there a dependency that I'm missing?

**Comment by alexcrichton** [comment]
Could you try running `cargo clean` and see if it reproduces?

**Comment by natemara** [comment]
I get the same error after a clean.

	F:\Coding\rust-deduper (master)
	$ cargo clean

	F:\Coding\rust-deduper (master)
	$ cargo build --verbose
	   Compiling rustc-serialize v0.2.12
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.2.12\src\lib.rs --crate-name rustc-serialize --crate-type lib -g -C metadata=db8cde5690079042 -C extra-filename=-db8cde5690079042 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps -Awarnings`
	   Compiling libc v0.1.2
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.1.2\rust\src\liblibc\lib.rs --crate-name libc --crate-type lib -g --cfg feature="default" --cfg feature="cargo-build" -C metadata=8d21de95f4de7169 -C extra-filename=-8d21de95f4de7169 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps -Awarnings`
	   Compiling log v0.2.2
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\log-0.2.2\src\lib.rs --crate-name log --crate-type lib -g -C metadata=6ccd07f1f8244a62 -C extra-filename=-6ccd07f1f8244a62 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps -Awarnings`
	   Compiling gcc v0.1.7
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.1.7\src\lib.rs --crate-name gcc --crate-type lib -g -C metadata=3361713823cacea0 -C extra-filename=-3361713823cacea0 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps -Awarnings`
	   Compiling rand v0.1.2
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.1.2\src\lib.rs --crate-name rand --crate-type lib -g -C metadata=786334d103466ef3 -C extra-filename=-786334d103466ef3 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps --extern log=F:\Coding\rust-deduper\target\deps\liblog-6ccd07f1f8244a62.rlib --extern libc=F:\Coding\rust-deduper\target\deps\liblibc-8d21de95f4de7169.rlib -Awarnings`
	   Compiling getopts v0.2.3
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\getopts-0.2.3\src\lib.rs --crate-name getopts --crate-type lib -g -C metadata=a6c123c21f99fb4b -C extra-filename=-a6c123c21f99fb4b --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps --extern log=F:\Coding\rust-deduper\target\deps\liblog-6ccd07f1f8244a62.rlib -Awarnings`
	   Compiling time v0.1.16
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\build.rs --crate-name build-script-build --crate-type bin -C prefer-dynamic -g --out-dir F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7 --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps --extern gcc=F:\Coding\rust-deduper\target\deps\libgcc-3361713823cacea0.rlib -Awarnings`
	     Running `F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\build-script-build.exe`
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src\lib.rs --crate-name time --crate-type lib -g -C metadata=69a93874bd2e0ce7 -C extra-filename=-69a93874bd2e0ce7 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps --extern libc=F:\Coding\rust-deduper\target\deps\liblibc-8d21de95f4de7169.rlib -Awarnings -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out -l static=time_helpers`
	   Compiling rust-crypto v0.2.15
	     Running `rustc C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-crypto-0.2.15\src\lib.rs --crate-name crypto --crate-type lib -g -C metadata=24da0b4009abc223 -C extra-filename=-24da0b4009abc223 --out-dir F:\Coding\rust-deduper\target\deps --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target\deps -L dependency=F:\Coding\rust-deduper\target\deps --extern time=F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib --extern rustc-serialize=F:\Coding\rust-deduper\target\deps\librustc-serialize-db8cde5690079042.rlib --extern rand=F:\Coding\rust-deduper\target\deps\librand-786334d103466ef3.rlib -Awarnings -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out`
	   Compiling deduper v0.0.1 (file:///F:/Coding/rust-deduper)
	     Running `rustc src\main.rs --crate-name deduper --crate-type bin -g --out-dir F:\Coding\rust-deduper\target --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target -L dependency=F:\Coding\rust-deduper\target\deps --extern crypto=F:\Coding\rust-deduper\target\deps\libcrypto-24da0b4009abc223.rlib --extern getopts=F:\Coding\rust-deduper\target\deps\libgetopts-a6c123c21f99fb4b.rlib -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out`
	src\main.rs:23:41: 23:47 warning: use of unstable library feature 'collections': likely to be renamed
	src\main.rs:23     let matches = match opts.parse(args.tail()) {
							       ^~~~~~
	src\main.rs:23:41: 23:47 help: add #![feature(collections)] to the crate attributes to silence this warning
	src\main.rs:23     let matches = match opts.parse(args.tail()) {
							       ^~~~~~
	src\main.rs:15:29: 15:37 warning: use of deprecated item: use env::args instead, #[warn(deprecated)] on by default
	src\main.rs:15     let args: Vec<String> = os::args();
						   ^~~~~~~~
	src\main.rs:70:13: 70:30 warning: unused result which must be used, #[warn(unused_must_use)] on by default
	src\main.rs:70             fs::unlink(&dup);
				   ^~~~~~~~~~~~~~~~~
	src\main.rs:72:9: 72:71 warning: unused result which must be used, #[warn(unused_must_use)] on by default
	src\main.rs:72         out_file.write_str(format!("{}\n", dup.display()).as_slice());
			       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	error: linking with `gcc` failed: exit code: 1
	note: "gcc" '"-Wl,--enable-long-section-names"' '"-fno-use-linker-plugin"' '"-Wl,--nxcompat"' '"-static-libgcc"' '"-m64"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-o"' '"F:\\Coding\\rust-deduper\\target\\deduper.exe"' '"F:\\Coding\\rust-deduper\\target\\deduper.o"' '"-Wl,--gc-sections"' '"F:\\Coding\\rust-deduper\\target\\deps\\libcrypto-24da0b4009abc223.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\libtime-69a93874bd2e0ce7.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\librustc-serialize-db8cde5690079042.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\librand-786334d103466ef3.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\liblibc-8d21de95f4de7169.rlib"' '"F:\\Coding\\rust-deduper\\target\\deps\\libgetopts-a6c123c21f99fb4b.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunicode-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-4e7c5e5c.rlib"' '"-L"' '"F:\\Coding\\rust-deduper\\target"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\deps"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\build\\time-69a93874bd2e0ce7\\out"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-L"' '"F:\\Coding\\rust-deduper\\.rust\\bin\\x86_64-pc-windows-gnu"' '"-L"' '"F:\\Coding\\rust-deduper\\bin\\x86_64-pc-windows-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lws2_32"' '"-luserenv"' '"-lcompiler-rt"'
	note: F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::tzset':
	C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:599: undefined reference to `rust_time_tzset'
	F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::at_utc':
	C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:703: undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::Tm::to_timespec':
	C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:733: undefined reference to `rust_time_timegm'
	C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:734: undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): In function `time::at':
	C:\Users\Nate\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.16\src/lib.rs:718: undefined reference to `rust_time_localtime'

	error: aborting due to previous error
	Could not compile `deduper`.

	Caused by:
	  Process didn't exit successfully: `rustc src\main.rs --crate-name deduper --crate-type bin -g --out-dir F:\Coding\rust-deduper\target --emit=dep-info,link -L dependency=F:\Coding\rust-deduper\target -L dependency=F:\Coding\rust-deduper\target\deps --extern crypto=F:\Coding\rust-deduper\target\deps\libcrypto-24da0b4009abc223.rlib --extern getopts=F:\Coding\rust-deduper\target\deps\libgetopts-a6c123c21f99fb4b.rlib -L native=F:\Coding\rust-deduper\target\build\time-69a93874bd2e0ce7\out` (status=101)

	warning: LF will be replaced by CRLF in Cargo.lock.
	The file will have its original line endings in your working directory.

**Comment by natemara** [comment]
I get some more information if I compile with `--release`

			       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	error: linking with `gcc` failed: exit code: 1
	note: "gcc" '"-Wl,--enable-long-section-names"' '"-fno-use-linker-plugin"' '"-Wl,--nxcompat"' '"-static-libgcc"' '"-m64"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-o"' '"F:\\Coding\\rust-deduper\\target\\release\\deduper.exe"' '"F:\\Coding\\rust-deduper\\target\\release\\deduper.o"' '"-Wl,--gc-sections"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\libcrypto-24da0b4009abc223.rlib"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\libtime-69a93874bd2e0ce7.rlib"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\librustc-serialize-db8cde5690079042.rlib"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\librand-786334d103466ef3.rlib"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\liblibc-8d21de95f4de7169.rlib"' '"F:\\Coding\\rust-deduper\\target\\release\\deps\\libgetopts-a6c123c21f99fb4b.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunicode-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-4e7c5e5c.rlib"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-4e7c5e5c.rlib"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\release"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\release\\deps"' '"-L"' '"F:\\Coding\\rust-deduper\\target\\release\\build\\time-69a93874bd2e0ce7\\out"' '"-L"' '"C:\\Rust\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-L"' '"F:\\Coding\\rust-deduper\\.rust\\bin\\x86_64-pc-windows-gnu"' '"-L"' '"F:\\Coding\\rust-deduper\\bin\\x86_64-pc-windows-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lws2_32"' '"-luserenv"' '"-lcompiler-rt"'
	note: F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0xf31): undefined reference to `rust_time_tzset'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x118a): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1194): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x11e9): undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1266): undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x12a6): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x12b0): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x131a): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1324): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1379): undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x13e7): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x13f1): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x140d): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1417): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x14c7): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x14d1): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x14ed): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x14f7): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1623): undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x16a6): undefined reference to `rust_time_localtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1773): undefined reference to `rust_time_localtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x17e6): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x17f0): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x181a): undefined reference to `rust_time_localtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1886): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x1890): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x18ba): undefined reference to `rust_time_gmtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x24ec): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x2643): undefined reference to `rust_time_timegm'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x2671): undefined reference to `rust_time_localtime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x3023): undefined reference to `rust_time_mktime'
	F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o):(.text+0x32ac): undefined reference to `rust_time_timegm'
	ld: F:\Coding\rust-deduper\target\release\deps\libtime-69a93874bd2e0ce7.rlib(time-69a93874bd2e0ce7.o): bad reloc address 0xc in section `.xdata'

	error: aborting due to previous error
	Could not compile `deduper`.

	To learn more, run the command again with --verbose.

	warning: LF will be replaced by CRLF in Cargo.lock.
	The file will have its original line endings in your working directory.

**Comment by alexcrichton** [comment]
What version of gcc are you currently using? Also, what sort of MSYS/mingw install are you using?

**Comment by natemara** [comment]
This is all the info I can find on my installed gcc

	F:\Coding\rust-deduper (master)
	$ where gcc
	C:\MinGW\bin\gcc.exe
	C:\tools\mingw64\bin\gcc.exe
	C:\strawberry\c\bin\gcc.exe

	F:\Coding\rust-deduper (master)
	$ gcc --version
	gcc (GCC) 4.8.1
	Copyright (C) 2013 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

![image](http://i.imgur.com/scMyewL.png)

**Comment by alexcrichton** [comment]
Having three gcc toolchains seems like it may cause problems. It may be the case that one toolchain is compiling `time_helpers.c` while another is actually linking the Rust program. Could you try ensuring that there's only one `gcc.exe` in your `PATH`? You may also want to be sure to install Rust *without* the linker and library support (as you already have them installed).

**Comment by natemara** [comment]
I think I figured it out. I had installed the x64 version of rust, but all of my gcc's are 32-bit. I installed 32-bit rust and it compiled just fine.
