### ISSUE TITLE
Overflow might happen easier on Windows

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/time#76]
See https://github.com/tomaka/clock_ticks/pull/4

clock_ticks is based on this library, so I suspect the same issue applies here.

https://github.com/rust-lang/time/blob/a9b589595eaffd9f5b6a4b53bc89a32246204ac2/src/lib.rs#L251

```Rust
return (ticks as u64 * 1000000000) / (imp::frequency() as u64);
```

**Comment by huonw** [comment]
cc https://github.com/rust-lang/rust/issues/17845, https://github.com/rust-lang/rust/pull/22788

**Comment by alexcrichton** [comment]
Applied the same fix as in the main repo, thanks!
