### ISSUE TITLE
Remove C dependencies

### ISSUE THREAD

**Issue by iopq** [rust-lang/time#78]
I recently had to compile a Rust project with time as a dependency and I went through a lot of trouble having to get mingw64 on my 64 bit machine and messing around with paths to make sure that's the version that's used and not the 32 bit version. (I have 64 bit Rust and 32 bit C mingw)

Is it possible to remove the C dependencies so this project uses only Rust? That would make compiling projects with time as a dependency much easier on Windows.

**Comment by rotanov** [comment]
I've bumped into the same problem. What's the workaround? Install x64 mingw and prepend it to %PATH%?

**Comment by aochagavia** [comment]
This is a major pain point for windows users

**Comment by majkcramer** [comment]
I run into the same issue. Will try x64 mingw as ratanov recommended....
