### ISSUE TITLE
build failed on osx, error: use of undeclared triat name `AsRef`

### ISSUE THREAD

**Issue by HeavenIke** [rust-lang/time#81]
$ rustc --version
rustc 1.0.0-dev (92dd995e1 2015-03-16) (built 2015-03-18)
$ cargo build
Compiling gcc v0.3.3
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:113:23: 113:34 error: use of undeclared trait name `AsRef`
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:113     pub fn include<P: AsRef<Path>>(&mut self, dir: P) -> &mut Config {
                                                                                                             ^~~~~~~~~~~
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:125:22: 125:33 error: use of undeclared trait name `AsRef`
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:125     pub fn object<P: AsRef<Path>>(&mut self, obj: P) -> &mut Config {
                                                                                                            ^~~~~~~~~~~
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:137:20: 137:31 error: use of undeclared trait name `AsRef`
/Users/heaven/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.3/src/lib.rs:137     pub fn file<P: AsRef<Path>>(&mut self, p: P) -> &mut Config {
                                                                                                          ^~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `gcc`.

**Comment by alexcrichton** [comment]
Currently most Rust libraries require a nightly build of rust to work, so if you update to nightly this should work itself out!
