### ISSUE TITLE
panic Tm::asctime on linux x86_64 systems

### ISSUE THREAD

**Issue by willem66745** [rust-lang/time#85]
Panic when using Tm::asctime at Linux x86_64:

(simplified to reproduce the problem)
```rust
extern crate time;
use time::{Timespec, at};

fn main() {
    println!("{}", at(Timespec::new(-0x800000000000000, 0)).asctime());
}
```
Results in a unreachable panic:
```
thread '<main>' panicked at 'internal error: entered unreachable code', /home/willem/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.22/src/display.rs:134
```

At Linux 32-bit system, no panic happens.

Problem is caused by a invalid Tm struct created by 'at':
```
Tm { tm_sec: 24, tm_min: 21, tm_hour: 17, tm_mday: 32693, tm_mon: 37, tm_year: -1087444786, tm_wday: 0, tm_yday: 32693, tm_isdst: 0, tm_utcoff: 1172, tm_nsec: 0 }
```

This actually not caused by time crate itself, but is caused by GNU libc implementation of 'localtime_r'.

**Comment by alexcrichton** [comment]
Oh dear, looks like we just weren't checking errors!
